export { default as StoreHeader } from './StoreHeader';
export { default as StoreBanner } from './StoreBanner';
export { default as FeaturedProducts } from './FeaturedProducts';
export { default as ProductCategories } from './ProductCategories';
export { default as StoreServices } from './StoreServices';
export { default as StoreAbout } from './StoreAbout';
export { default as StoreContact } from './StoreContact';
export { default as StoreFooter } from './StoreFooter';
export { default as StorePage } from './StorePage'; 