ignoredBuiltDependencies:
  - '@heroui/shared-utils'
  - '@journeyapps/wa-sqlite'
  - '@parcel/watcher'
  - '@swc/core'
  - better-sqlite3
  - core-js
  - cwebp-bin
  - electron
  - electron-winstaller
  - esbuild
  - gifsicle
  - javascript-obfuscator
  - jpegtran-bin
  - keytar
  - mozjpeg
  - optipng-bin
  - pngquant-bin
  - puppeteer
  - sharp
  - sqlite3
  - workerd

overrides:
  phin@<3.7.1: '>=3.7.1'
