// supabase/functions/_shared/types.ts

export const corsHeaders = {
  'Access-Control-Allow-Origin': '*', // Consider restricting this in production
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, prefer, x-supabase-edge-redirect-to',
  'Access-Control-Allow-Methods': 'POST, GET, OPTIONS, PUT, DELETE', // Add other methods as needed
};

export enum AbandonedCartStatus {
  PENDING = 'pending',
  CONTACTED = 'contacted',
  CONVERTED = 'converted',
  CLOSED = 'closed',
}

export interface AbandonedCartItem {
  product_id: string; // Assuming product_id is a string (UUID or custom ID)
  variant_id?: string | null; // Can be null or undefined if no variant
  quantity: number;
  name?: string; // Optional: for display purposes, not for core logic
  price?: number; // Optional: price at the time of abandonment
  // Add any other relevant item details, e.g., SKU, image_url
}

export interface CustomFieldData {
  name: string;
  value: string | number | boolean | string[] | null; // Allow null for optional fields
  // You might want to add 'label' or 'type' if needed for rendering or processing
}

export interface AbandonedCartData {
  id?: string; // Optional: ID can be generated by DB or assigned if updating
  organization_id: string; // UUID, foreign key to your organizations table
  customer_name?: string | null;
  customer_phone: string; // Assuming this is a key identifier
  customer_email?: string | null;
  customer_address?: string | null; // Or a more structured address object
  province?: string | null; // Added field
  municipality?: string | null; // Added field
  product_id?: string | null; // Root product ID
  product_color_id?: string | null; // Root product color ID
  product_size_id?: string | null; // Root product size ID
  quantity?: number | null; // Root quantity for the single product context
  cart_items: AbandonedCartItem[];
  custom_fields_data?: CustomFieldData[] | null; // Array of custom field key-value pairs
  currency?: string | null; // e.g., 'DZD', 'USD', 'EUR'
  subtotal?: number | null;
  calculated_delivery_fee?: number | null; // Renamed from shipping_cost
  total_amount?: number | null;
  delivery_option?: string | null; // Added field
  payment_method?: string | null; // Added field
  notes?: string | null; // Notes from customer or internal notes
  status?: AbandonedCartStatus; // Enum for cart status
  created_at?: string; // ISO date string, managed by DB
  updated_at?: string; // ISO date string, managed by DB
  // Additional potentially useful fields:
  // recovery_attempts?: number;
  // last_recovery_attempt_at?: string; // ISO date string
  // source_url?: string; // The URL where the cart was abandoned
  // discount_codes?: string[];
  // metadata?: Record<string, any>; // For any other unstructured data
}
